[versions]
activityComposeVersion = "1.7.2"
appcompatVersion = "1.6.1"
coreKtxVersion = "1.10.1"
kamelImageVersion = "0.6.0"
koinCoreVersion = "3.2.2"
koinComposeVersion = "1.0.4"
kotlinxSerializationJsonVersion = "1.5.1"
precomposeVersion = "1.4.3"
firebaseVersion = "1.8.0"


[libraries]

kamel-image = { module = "media.kamel:kamel-image", version.ref = "kamelImageVersion" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJsonVersion" }

activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinCoreVersion" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koinComposeVersion" }

precompose-core = { module = "moe.tlaster:precompose", version.ref = "precomposeVersion" }
precompose-viewmodel = { module = "moe.tlaster:precompose-viewmodel", version.ref = "precomposeVersion" }

firebase-firestore = {module = "dev.gitlive:firebase-firestore",version.ref = "firebaseVersion"}


[bundles]
android = [
    "activity-compose",
    "appcompat",
    "core-ktx"
]
precompose = [
    "precompose-core",
    "precompose-viewmodel"
]