[versions]
activityComposeVersion = "1.10.0"
delightVersion = "2.0.1"
appcompatVersion = "1.7.0"
chartsVersion = "1.0.4"
coreKtxVersion = "1.15.0"
koinVersion = "4.0.0"
kotlinxCollectionsImmutableVersion = "0.3.7"
kotlinxCoroutinesTestVersion = "1.10.1"
composeKtlintVersion = "1.4.2"
androidx-navigation = "2.8.0-alpha12"
datetimeVersion = "0.6.0"
kotlinStdlibVersion = "2.1.10"
orbit = "9.0.0"
androidVersion = "8.3.2"
composeVersion = "1.6.11"
ktlintVersion = "4.4.1"
turbineVersion = "1.1.0"
kotlin = "2.0.0"
modulegraph = "0.10.0"
androidx-lifecycle = "2.8.4"
app-compile-sdk = "35"
app-min-sdk = "24"
java-jdk = "17"

[libraries]
charts = { module = "com.carlosgub.kotlinm.charts:charts", version.ref = "chartsVersion" }

activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinVersion" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinVersion" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koinVersion" }
koin-compose-viewmodel = {module = "io.insert-koin:koin-compose-viewmodel",version.ref = "koinVersion"}

ktlint = { module = "com.slack.lint.compose:compose-lint-checks", version.ref = "composeKtlintVersion" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetimeVersion" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutableVersion" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-common", version.ref = "kotlinStdlibVersion" }

delight-android = { module = "app.cash.sqldelight:android-driver", version.ref = "delightVersion" }
delight-ios = { module = "app.cash.sqldelight:native-driver", version.ref = "delightVersion" }
delight-extension = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "delightVersion" }

orbit_core = { module = "org.orbit-mvi:orbit-core", version.ref = "orbit" }
orbit_testing = { module = "org.orbit-mvi:orbit-test", version.ref = "orbit"}

kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTestVersion" }

turbine = { module = "app.cash.turbine:turbine", version.ref = "turbineVersion" }

[bundles]
android = [
    "activity-compose",
    "appcompat",
    "core-ktx"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidVersion"}
android-library = { id = "com.android.library", version.ref = "androidVersion"}
compose = { id = "org.jetbrains.compose", version.ref = "composeVersion"}
sqldelight = { id = "app.cash.sqldelight", version.ref = "delightVersion"}
ktlint = { id = "org.jmailen.kotlinter", version.ref = "ktlintVersion"}
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
modulegraph = {id = "dev.iurysouza.modulegraph", version.ref = "modulegraph"}
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
