[versions]
activityComposeVersion = "1.7.2"
appcompatVersion = "1.6.1"
coreKtxVersion = "1.10.1"
kamelImageVersion = "0.6.0"
koinCoreVersion = "3.2.2"
koinComposeVersion = "1.0.4"
kotlinxSerializationJsonVersion = "1.5.1"
ktorClientCoreVersion = "2.3.1"
voyagerVersion = "1.0.0-rc05"


[libraries]

kamel-image = { module = "media.kamel:kamel-image", version.ref = "kamelImageVersion" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJsonVersion" }

activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinCoreVersion" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koinComposeVersion" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinCoreVersion" }

ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktorClientCoreVersion" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorClientCoreVersion" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorClientCoreVersion" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktorClientCoreVersion" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorClientCoreVersion" }

voyager-bottom-sheet-navigator = { module = "cafe.adriel.voyager:voyager-bottom-sheet-navigator", version.ref = "voyagerVersion" }
voyager-core = { module = "cafe.adriel.voyager:voyager-core", version.ref = "voyagerVersion" }
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyagerVersion" }
voyager-tab-navigator = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyagerVersion" }
voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyagerVersion" }

[bundles]
voyager = [
    "voyager-bottom-sheet-navigator",
    "voyager-core",
    "voyager-navigator",
    "voyager-tab-navigator",
    "voyager-transitions"
]
ktor = [
    "ktor-client-content-negotiation",
    "ktor-client-core",
    "ktor-serialization-kotlinx-json"
]
android = [
    "activity-compose",
    "appcompat",
    "core-ktx"
]