name: Check code style
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  G_USERNAME: ${{vars.G_USERNAME}}
  G_TOKEN: ${{vars.G_TOKEN}}

jobs:
  check-code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Check code style
        shell: bash
        run: ./gradlew lintKotlin
  run-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: "Test Username"
        run: echo "$G_USERNAME"
      - name: Run Unit Test Android Shared Module
        shell: bash
        run: ./gradlew :shared:testDebugUnitTest
      - name: Run Unit Test Android Data Module
        shell: bash
        run: ./gradlew :data:testDebugUnitTest
      - name: Run Unit Test iOS Shared Module
        shell: bash
        run: ./gradlew :shared:iosSimulatorArm64Test
      - name: Run Unit Test iOS Data Module
        shell: bash
        run: ./gradlew :data:iosSimulatorArm64Test
