name: Check code style
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Check code style
        shell: bash
        run: ./gradlew lintKotlin
  run-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: "Test Username"
        run: echo "${{vars.G_USERNAME}}"
      - name: Run Unit Test Android
        shell: bash
        run: ./gradlew :shared:testDebugUnitTest
      - name: Run Unit Test iOS
        shell: bash
        run: ./gradlew :shared:iosSimulatorArm64Test
